name: shared_core
description: "Shared code for AssignMate Mobile and Desktop"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  flutter_bloc: ^9.1.1
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  google_sign_in: ^7.1.1
  extension_google_sign_in_as_googleapis_auth: ^3.0.0
  path_provider: ^2.1.5
  http: ^1.5.0
  cloud_firestore: ^6.0.0
  firebase_core: ^4.0.0
  file_picker: ^10.3.1
  record: ^6.1.0
  audioplayers: ^6.5.0
  url_launcher: ^6.3.2
  firebase_auth: ^6.0.1
  go_router: ^16.1.0
  firebase_app_check: ^0.4.0
  floor: ^1.5.0
  sqflite: ^2.4.2
  mutex: ^3.1.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.4.0
  timezone: ^0.10.1
  google_fonts: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.4.2
  build_runner: ^2.1.2
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/google.png

