// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXAvcCWPSo_-o_qgj7Z4f4JMggp6DMwd0',
    appId: '1:731983346773:android:6bda815c1022635f30e8dc',
    messagingSenderId: '731983346773',
    projectId: 'assignmate-29d27',
    storageBucket: 'assignmate-29d27.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPA_cs53Ffu5YiIPpIHyHLWwuFBqhtdm4',
    appId: '1:731983346773:ios:b34e2fa6c6b1c8f330e8dc',
    messagingSenderId: '731983346773',
    projectId: 'assignmate-29d27',
    storageBucket: 'assignmate-29d27.firebasestorage.app',
    androidClientId: '731983346773-iaom4ei5jb5udgsqc0sirjj1jgo1gu1v.apps.googleusercontent.com',
    iosClientId: '731983346773-2dr474ara81edk28neh4fob3v6gketfo.apps.googleusercontent.com',
    iosBundleId: 'io.github.justincodinguk.assignmate',
  );

}