// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG5pAUfQypqFBW9Oj2y0CRmQptZHBnEuc',
    appId: '1:377457284475:android:614bc256eb0279e173d9de',
    messagingSenderId: '377457284475',
    projectId: 'assignmatebackend',
    storageBucket: 'assignmatebackend.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmbZJxlpeiCpxW7IS8T3l5rJibtIJlWGA',
    appId: '1:377457284475:ios:4eb16709bb4e699973d9de',
    messagingSenderId: '377457284475',
    projectId: 'assignmatebackend',
    storageBucket: 'assignmatebackend.firebasestorage.app',
    androidClientId: '377457284475-0sjjg4pfnrql6tlf6mm5j1anh203hmb8.apps.googleusercontent.com',
    iosClientId: '377457284475-gngs836jph5o536aat21bvss50hemc4t.apps.googleusercontent.com',
    iosBundleId: 'io.github.justincodinguk.assignmate',
  );

}