import 'dart:math';

import '../bloc/auth_bloc.dart';
import '../ext/pad.dart';
import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

class TimedGreeting extends StatelessWidget {
  const TimedGreeting({super.key});

  @override
  Widget build(BuildContext context) {
    String time;
    final isAdmin = context.read<AuthBloc>().isAdmin();

    final String affirmation;

    if (isAdmin) {
      affirmation = crAffirmations[Random().nextInt(crAffirmations.length)];
    } else {
      affirmation =
          studentAffirmations[Random().nextInt(studentAffirmations.length)];
    }

    final hour = DateTime.now().hour;
    if (hour < 12) {
      time = 'Morning';
    } else if (hour < 17) {
      time = 'Afternoon';
    } else {
      time = 'Evening';
    }

    if (isAdmin) {
      time += ", CR! o7";
    }

    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          "Good $time",
          style: Theme.of(context).textTheme.displayMedium!.copyWith(fontWeight: FontWeight.bold),
          textAlign: TextAlign.start,
        ).pad(16),
        Text(affirmation).padSymmetric(vertical: 8, horizontal: 16)
      ],
    );
  }
}

const studentAffirmations = [
  "I will pass… even if my calculator is smarter than me.",
  "I am not procrastinating… I am prioritizing panic later.",
  "My brain has 2TB of storage but only 2MB of RAM.",
  "I am calm. I am zen. I am crying internally.",
  "I will finish this assignment… eventually… maybe… who knows.",
  "I believe in myself… unlike my GPA.",
  "Never gonna give you up",
  "Every time I open the book, knowledge *definitely* goes in… right?",
  "I am not lazy, I am energy-efficient.",
  "Sleep is for the weak… and the employed.",
  "I will not drop out… today.",
  "My handwriting is a secret code… even to me.",
  "I will stop binge-watching… after one more episode.",
  "Grades don’t define me… but they definitely haunt me.",
  "My Wi-Fi is my spirit animal—unreliable and slow.",
  "I will pass the exam… out of pure pity.",
  "I am a productivity machine… that forgot to turn on.",
  "I believe coffee is a valid replacement for sleep.",
  "My brain has buffering issues.",
  "I am not lost, I am exploring the syllabus.",
  "I am allergic to deadlines, that’s why I avoid them.",
  "I can do hard things… after complaining for 2 hours.",
  "Knowledge is power… which is why I’m powerless.",
  "I am not stressed, I am just permanently vibrating.",
  "C’s get degrees, and I am basically a degree magnet.",
  "I am focused… until my phone buzzes.",
  "My brain is like Google… except with no results found.",
  "I believe in miracles… like finishing homework on time.",
  "I am the hero my assignment doesn’t deserve.",
  "I will get through this… with tears and snacks.",
  "I am not unprepared, I am creatively improvising.",
  "Tomorrow-me will handle it. Tomorrow-me is a champ.",
  "I will not cry. I will not cry. I will maybe cry.",
  "My brain is Wi-Fi: weak signal, but still somehow connected.",
  "I am studying… my own patience limits.",
  "I will pass this course through sheer confusion.",
  "I believe in late-night panic-fueled genius.",
  "I am writing notes I will never read again.",
  "I will graduate… eventually… hopefully… maybe…",
  "My brain has 99 tabs open and 98 are frozen.",
  "I am absorbing information osmosis-style… by sleeping on the book.",
  "I am smart… selectively.",
  "I will not throw the textbook out the window… yet.",
  "I am one assignment away from enlightenment.",
  "I will not compare myself to toppers… they are aliens.",
  "My motivation is hiding under the bed.",
  "I believe in short breaks… every 5 seconds.",
  "I am prepared for this test… in an alternate universe.",
  "I am learning… mostly new ways to procrastinate.",
  "I am academically surviving on vibes.",
  "My attention span is shorter than this sentence.",
  "I will stop scrolling Instagram… after this one meme.",
  "I am a scholar… of random YouTube rabbit holes.",
  "I am strong enough to carry my GPA’s disappointment.",
  "I believe in the power of guessing.",
  "I am not failing, I am just testing the limits of the grading system.",
  "I will thrive… like a plant in the desert.",
  "I am not confused, I am open-minded.",
  "I believe in myself… sometimes… maybe… on weekends.",
  "I am a genius… when the exam is over.",
  "My brain is loading… please wait…",
  "I am focused on studying… the ceiling fan.",
  "I am the definition of academic chaos.",
  "I believe in caffeine, not confidence.",
  "I am not ignoring my notes… they are ignoring me.",
  "I will survive on 4 hours of sleep… hopefully.",
  "I am full of potential… and anxiety.",
  "I am a scholar of last-minute miracles.",
  "I believe the syllabus is a work of fiction.",
  "I am motivated by fear… and snacks.",
  "I am calm… until I see the word 'exam'.",
  "I will not break down… publicly.",
  "I am not procrastinating… I am curating stress.",
  "I am preparing… mentally, not academically.",
  "I will not throw my laptop out the window… today.",
  "I am not sleepy, I am just horizontal-thinking.",
  "I am a knowledge sponge… currently dry.",
  "I believe in survival, not success.",
  "I am a scholar of selective memory.",
  "I am working hard… or hardly working.",
  "I am not behind, I am fashionably late to the syllabus.",
  "I am not stressed, I am pressure-tested.",
  "I believe the exam will pass me.",
  "I am powered by deadlines and despair.",
  "I am not dumb, I am just under construction.",
  "I am learning… slowly… painfully… loudly.",
  "I will not panic… loudly.",
  "I am calm… like a bomb.",
  "I believe in guessing C for every MCQ.",
  "I am smart… at everything except exams.",
  "I am studying… the wall paint.",
  "I am alive… unfortunately.",
  "I am not failing, I am exploring alternative success routes.",
  "I will not burn the textbook… probably.",
  "I believe in memes more than methods.",
  "I am academically flexible… meaning I bend until I break.",
  "I am a master of strategic crying.",
  "I am not out of time… the clock is lying.",
  "I am thriving… on zero motivation.",
  "I am a professional deadline-dodger.",
  "I will not scream… loudly.",
  "I believe in dumb luck.",
  "I am passing… barely sliding through life like butter on a pan.",
];

const crAffirmations = [
  "THESE PEASANTS!",
  "I don’t attend the class, the class attends me.",
  "If attendance had a face, it would salute me.",
  "I’m not the CR, I’m the CEO of Roll Numbers.",
  "People don’t call me CR, they call me CTRL + R because I refresh the whole class.",
  "Even Wi-Fi asks me for the password.",
  "When I bunk, the whole class gets mass bunk by default.",
  "I don’t raise my hand, I raise the standard.",
  "Teachers don’t give me assignments, they ask for my approval.",
  "I’m not a bridge between students and teachers—I’m the entire highway.",
  "My signature on the proxy sheet is considered authentic attendance.",
  "The projector doesn’t work until I enter the class.",
  "I don’t set reminders; the timetable sets itself for me.",
  "Even the blackboard feels honored when I pick up the chalk.",
  "When I sneeze, the class gets a holiday.",
  "I’m not the voice of the students, I’m the sound system.",
  "I don’t forward notices, I issue decrees.",
  "The bell doesn’t ring to end the lecture, it rings to mark my departure.",
  "If I sit in the backbench, it automatically becomes the frontbench.",
  "I’m not a CR, I’m an ecosystem.",
  "I don’t maintain the class list, I maintain the class legacy.",
  "Group chats exist only because I allow them.",
  "Even PowerPoint slides wait for my approval before moving forward.",
  "I don’t mediate between teachers and students, I manage international relations.",
  "Roll call is just a playlist where my name is the headliner.",
  "The Wi-Fi speed doubles when I join the class.",
  "Even assignments get extended deadlines out of respect for me.",
  "My presence itself is internal marks.",
  "I don’t raise doubts; I raise hopes.",
  "Google Classroom asks me before sending notifications.",
  "I don’t take attendance, attendance takes me.",
  "The class doesn’t run on schedule; it runs on my mood.",
  "I’m not the representative of students; I’m their overlord.",
  "Even the principal calls me ‘beta’.",
  "When I laugh, the class finds it hilarious by law.",
  "I don’t join the Zoom meeting, the Zoom meeting joins me.",
  "If I go offline, even electricity feels useless.",
  "I’m the reason ‘Reply All’ was invented.",
  "People say ‘Knowledge is power’. I say ‘CR is ultimate power’.",
  "When I’m absent, the classroom feels like an empty stadium.",
  "Even proxies ask me for guidance.",
  "I don’t send reminders, I send ultimatums.",
  "The chalk breaks out of respect when I touch it.",
  "When I write on the board, it’s considered published research.",
  "I’m not the CR, I’m the syllabus coordinator.",
  "Even teachers copy-paste from my notes.",
  "When I announce a test, half the class cries instantly.",
  "I’m not the reason classes run smoothly, I *am* the smoothness.",
  "Even the classroom clock runs on my time zone.",
  "Group projects succeed only because I exist.",
  "If I’m late, it’s called a delay in history.",
  "I don’t send PDFs, I send destiny files.",
  "The mic works only in my presence.",
  "Even chalk dust feels proud to settle on me.",
  "I’m not a rep, I’m the reincarnation of authority.",
  "The teacher doesn’t say, ‘Class, settle down’; they say, ‘CR, help me’.",
  "Even Microsoft Teams apologizes if I lag.",
  "When I skip class, students panic like it’s the stock market crash.",
  "I don’t announce room changes, I relocate the universe.",
  "I’m not just the class rep—I’m the class royalty.",
  "Teachers don’t scold me, they negotiate.",
  "If I bunk, it’s called an administrative leave.",
  "I’m not the CR, I’m the syllabus timeline.",
  "Even campus Wi-Fi checks in with me before working.",
  "When I enter the class, attendance is already 100%.",
  "I don’t handle complaints; I declare verdicts.",
  "The chalkboard becomes a smart board when I touch it.",
  "Even the fan rotates only with my nod.",
  "When I whisper, the notice becomes official.",
  "I’m not a CR, I’m the class constitution.",
  "Group chats without me are illegal gatherings.",
  "Even teachers wait for my ‘okay’ before starting lectures.",
  "I don’t just forward messages, I create history.",
  "The timetable gets edited when I blink.",
  "When I type in the WhatsApp group, silence prevails.",
  "I’m not the class representative—I’m the class brand ambassador.",
  "Even proxy attendances are loyal to me.",
  "I don’t just call names during attendance, I announce greatness.",
  "When I sit for an exam, the question paper feels nervous.",
  "I’m the CR, not a helpdesk.",
  "Even the canteen guy knows my deadlines.",
  "I don’t request leave, I declare national holidays.",
  "If I mute the class group, civilization halts.",
  "I’m not a CR, I’m a CR-7 of academics.",
  "Even the photocopy machine respects me.",
  "The syllabus waits for my nod before being covered.",
  "I don’t wait for instructions, I issue protocols.",
  "The benches align automatically when I enter.",
  "Even the lab instruments salute me.",
  "When I walk into the exam hall, the invigilator says ‘Good luck, sir’.",
  "I’m not a CR, I’m a one-man faculty.",
  "Even deadlines run away from me.",
  "If I type ‘Noted’, the entire class bows.",
  "When I bunk, mass bunk becomes the law.",
  "I don’t announce viva dates, I declare them as festivals.",
  "Even the printer knows my roll number.",
  "When I say ‘Relax’, the exam gets postponed.",
  "I’m not a CR, I’m the final authority.",
  "The whiteboard markers never run out for me.",
  "Even semester results hesitate before showing up to me.",
  "I don’t just manage the class—I own it.",
  "When I say ‘Class dismissed’, history is written.",
];
